theme: jekyll-theme-cayman
author: EA
title: Credit Card Fraud Detection and Model Evaluation
description: Based on assignments from Applied Machine Learning in Python by University of Michigan on Coursera
show_downloads: true
github:
  zip_url: https://eagronin.github.io/portfolio/
  tar_url: https://www.linkedin.com/in/eagronin
